### PR TITLE
CORE-6178 Virtual node uniqueness database support

### PR DESCRIPTION
**Pull request by relyafi**
### Summary

This change introduces a separate "uniqueness" virtual node database connection. This database serves the same purpose as the notary backing database in the Corda 4 HA notary implementation, and is used to store transaction and state information used as part of uniqueness checks.

This PR follows the same provisioning pattern as the existing crypto and vault DBs; an existing database can be specified explicitly by specifying `uniquenessDdlConnection` and `uniquenessDmlConnection` arguments on the virtual node creation API. If these arguments are not specified, then a new database schema will be automatically provisioned against the cluster database, with a name of the form `vnode_uniq_<holding id short hash>`.

Functionally, the uniqueness database is optional, as currently only notary virtual nodes will require this database. Optionality is considered to be a future enhancement to be addressed by [CORE-6541](https://r3-cev.atlassian.net/browse/CORE-6541).

This change only implements the provisioning of the uniqueness database. The uniqueness checker will be enhanced to select the appropriate uniqueness database based on holding id in [CORE-4718](https://r3-cev.atlassian.net/browse/CORE-4718).

### Testing
- Existing automated test cases enhanced with new arguments and confirmed to continue to pass
- New test case added to `VirtualNodeWriterProcessorTests` to ensure incorrect argument behavior matches other database connections
- Manual testing to confirm a uniqueness DB is provisioned on virtual node creation if an explicit connection is not supplied, and an existing database is used if connections details are supplied.

### CODE REVIEW

**Review by driessamyn — COMMENTED** [review]
Change looks conceptually good to me. It would be good to get @vkolomeyko's approval also as it touches on node lifecycle.

**Review by vkolomeyko — DISMISSED** [review]
LGTM

**Comment by nkovacsx** [comment]
Before approving: There's a minor inconsistency when using DML/Dml and DDL/Ddl. Sometimes they're all capital, sometimes only the first letter. Can we make sure this is consistent throughout the code? Otherwise, looks good.

**Review by nkovacsx — DISMISSED** [review]
Discussed it with @relyafi and seems like changing everything to use the same case would be quite painful at this point so approving.

**Review by vkolomeyko — APPROVED** [review]

**Pull request merged**
