### PR TITLE
CORE-4428 Update Gateway to use new JSON Schema

### PR DESCRIPTION
**Pull request by williamvigorr3**
Changed the gateway config key from "p2p.gateway" to "corda.p2p.gateway". Also renamed "maximalReconnectionDelay" to "maxReconnectionDelay" in gateway config. Merge  https://github.com/corda/corda-api/pull/464 first.

Testing with https://github.com/corda/corda-api/pull/464 (I used composite builds):
=====
From the `corda-dev-helm` repo. Deploy the perquisites with Kafka Broker Authentication disabled:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm dependency build charts/corda-dev
helm upgrade --install prereqs -n corda \
  charts/corda-dev \
  --set kafka.replicaCount=1,kafka.zookeeper.replicaCount=1 \
  --render-subchart-notes \
  --timeout 10m \
  --values=values.yml \
 --wait
```
Where `values.yml` contains:
```
kafka:
  auth:
    clientProtocol: plaintext
```

Edit the `values.yaml` file inside `corda-runtime-os` to turn TLS off in the Kafka Clients:
```
kafka:
  bootstrapServers: prereqs-kafka:9092
  replicas: 1
  tls:
    enabled: false
    truststore:
      secretRef:
        name: prereqs-kafka-0-tls
```

Deploy all the workers:
```
helm install corda -n corda  \
  charts/corda \
  --values values.yaml \
  --wait
```
Start kubefewd (so we can connect to Kafka outside of K8s):
```
sudo kubefwd svc -n corda
```
Start up the gateway:
```
java -jar applications/p2p-gateway/build/bin/corda-p2p-gateway-5.0.0.0-SNAPSHOT.jar --kafka-servers=prereqs-kafka:9092
```

The gateway should start up with the default config:
```
14:29:22.574 [Thread-3] INFO  Console - Gateway is running
```
Inside the gateways log (`logs/corda.log`) we can see lines like:
```
2022-07-07 14:29:21.768 [lifecycle-coordinator-2] INFO  net.corda.p2p.gateway.messaging.internal.ConnectionConfigReader - New configuration, connection settings updated to ConnectionConfiguration(maxClientConnections=100, acquireTimeout=PT0.01S, connectionIdleTimeout=PT0.06S, responseTimeout=PT1S, retryDelay=PT1S, initialReconnectionDelay=PT0.001S, maximalReconnectionDelay=PT0.016S).
```

Testing updating the config through the RPC worker
---
Expose the RPC end point outside of K8s
```
kubectl port-forward --namespace corda deployment/corda-rpc-worker 8888
```
For example to update the port:
```
curl --insecure -u admin:admin  -X PUT -d @config.json  https://localhost:8888/api/v1/config
Handling connection for 8888
{"section":"corda.p2p.gateway","config":"{ hostPort: 8088  }","schemaVersion":{"major":1,"minor":0},"version":1}%
```
Where `config.json` contains:
```
{
  "request": {
      "config": "{ hostPort: 8088  }",
      "schemaVersion": {
          "major": 1,
          "minor": 0
      },
      "section": "corda.p2p.gateway",
      "version": 0
  }
}
```
Another example updating the revocation check mode:
Where `config.json` contains:
```
{
  "request": {
      "config": "{ \"sslConfig\": { \"revocationCheck\": { \"mode\": \"HARD_FAIL\" }  }  }",
      "schemaVersion": {
          "major": 1,
          "minor": 0
      },
      "section": "corda.p2p.gateway",
      "version": 1
  }
}
```

I also checked the K8s p2p deployment still works.

### CODE REVIEW

**Review by yift-r3 — DISMISSED** [review]

**Review by dimosr — COMMENTED** [review]
Should we now be using the `P2P_GATEWAY_CONFIG` constant from corda-api? I think for the `p2p-setup` bits, we might have to get rid of the "$packageName.$componentName" format and just use the full key to do that.

**Comment by williamvigorr3** [comment]
> Should we now be using the `P2P_GATEWAY_CONFIG` constant from corda-api? I think for the `p2p-setup` bits, we might have to get rid of the "$packageName.$componentName" format and just use the full key to do that.

Let's do that. I will have to do an API bump.

**Comment by williamvigorr3** [comment]
> > Should we now be using the `P2P_GATEWAY_CONFIG` constant from corda-api? I think for the `p2p-setup` bits, we might have to get rid of the "$packageName.$componentName" format and just use the full key to do that.
> 
> Let's do that. I will have to do an API bump.

Actually we can avoid the bump if we merge https://github.com/corda/corda-api/pull/464 first + I rerun the PR gates after.

**Review by dimosr — DISMISSED** [review]
LGTM

**Review by dimosr — DISMISSED** [review]
LGTM - just waiting for a green build with the alpha version from corda-api and the testing with SOFT_FAIL and then I will proceed with merging

**Comment by dimosr** [comment]
seems to have conflicted, so needs another sync

**Review by dimosr — APPROVED** [review]

**Pull request merged**
