### PR TITLE
CORE-8151 Provide default digest algorithm and supported digest algorithms APIs

### PR DESCRIPTION
**Pull request by kyriathar**
- adds and implements default digest algorithm and supported digest algorithms for `PlatformDigestService` to return platform default and supported digest algorithms.
- implements default digest algorithm and supported digest algorithms for `DigestServiceImpl` to delegate to `PlatformDigestService` for platform digest algorithms and also delegate to per sandbox list of custom digest algorithms.

api PR: [#1045](https://github.com/corda/corda-api/pull/1045)

### CODE REVIEW

**Review by mnesbit — DISMISSED** [review]
OK

**Review by mnesbit — DISMISSED** [review]
OK

**Review by mnesbit — APPROVED** [review]
OK

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]
lgtm - build

**Pull request merged**
