### PR TITLE
NOTICK: DP2 -> Release merge 19/09/2022

### PR DESCRIPTION
**Pull request by JamesHR3**
Merge of the DP2 branch into the release branch.

Contains:
- CORE-6765
- CORE-6300
- CORE-6754
- CORE-6755
- CORE-6670
- CORE-6725
- CORE-6752
- CORE-6762

### CODE REVIEW

**Review by fowlerrr — DISMISSED** [review]
My doc change looks okay

**Review by ronanbrowne — DISMISSED** [review]
LGTM my changes

**Review by LizR3 — DISMISSED** [review]

**Review by yift-r3 — DISMISSED** [review]
LGTM

**Review by vkolomeyko — DISMISSED** [review]
LGTM

Reminder: Please do not squash

**Review by driessamyn — APPROVED** [review]
Ok for VNode and CPI doc changes.

**Review by yift-r3 — APPROVED** [review]

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
