### PR TITLE
NOTICK: fix build pin to correct version for DP2

### PR DESCRIPTION
**Pull request by ronanbrowne**
fixing version to unblock, this should be updated to be retrieved dynamically though and not hard coded

### CODE REVIEW

**Review by benmcmahon100 — DISMISSED** [review]

**Review by benmcmahon100 — COMMENTED** [review]
Small fix for irregular versions

**Comment by ronanbrowne** [comment]
Approved @benmcmahon100 changes to this branch, which were required to enable combined worker e2e tests to pass.

**Comment by benmcmahon100** [comment]
Just as an FIY going forward - the regex doesn't work if the version doesn't lead with `\d\.<something>`. This is fine as all our proper versions will conform to this syntax.

**Review by benmcmahon100 — APPROVED** [review]
Approving overall

**Pull request merged**
