### PR TITLE
CORE-10509 no error thrown for added characters on identity short hash 

### PR DESCRIPTION
**Pull request by pmck91**
"Getting a successful response when we try to associate CPI with an invalid 13-digit holding ID (i.e., after adding one digit after the valid holding ID)"

### CODE REVIEW

**Review by conal-smith — CHANGES_REQUESTED** [review]
I misread this ticket firstly, but I'm pretty sure we don't want to say "the CPI file checksum you're giving us has to be 12 characters or less".

The ticket is actually talking about the virtualNodeShortHash they provided was 13 characters. In this case, it is important because the vnode short hash is a field returned on the GET virtualnode endpoint and has 12 characters.

It looks like they didn't get error message "Hex string has length of ${hexString.length} but should be at least $LENGTH characters" because there is not validation on length being longer, and the following line only takes the first 12 characters when creating the shortHash, so the extra "1" they added to the vnodeShortHash was ignored:

https://github.com/corda/corda-runtime-os/blob/18bef8e022eb9055e425a5b86aa17e74e00a4ee5/libs/crypto/crypto-core/src/main/kotlin/net/corda/crypto/core/ShortHash.kt#L34

Possible fix: add validation to ShortHash.of to check the hexString should not be > LENGTH. What do you think @vkolomeyko ?

**Review by emilybowe — COMMENTED** [review]
Along with @conalsmith-r3 's point I would also add unit testing

**Comment by vkolomeyko** [comment]
> Possible fix: add validation to ShortHash.of to check the hexString should not be > LENGTH. What do you think @vkolomeyko ?

Yes, that would make sense to me.

**Review by conal-smith — APPROVED** [review]
lgtm, lets see if the build goes green or if this change impacts any other tests.

**Pull request closed without merging**
