### PR TITLE
CORE-16313: Upgrade Gradle 8.1.1 -> 8.2.1.

### PR DESCRIPTION
**Pull request by chrisr3**
Upgrade Gradle 8.1.1 -> 8.2.1.

- Include the `junit-platform-launcher` dependency explicitly, ready for Gradle 9. Note that Gradle will determine the correct version to use automatically by consulting JUnit's BOM.
- Also upgrade Gradle Enterprise plugin 3.12.2 -> 3.14.1.

### CODE REVIEW

**Review by wzur-r3 — DISMISSED** [review]
LGTM

**Review by wzur-r3 — APPROVED** [review]
LGTM

**Review by LWogan — APPROVED** [review]
LGTM

**Review by yift-r3 — APPROVED** [review]

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Review by yarivus — COMMENTED** [review]
thx @chrisr3

**Pull request merged**
