### PR TITLE
CORE-6661: Produce `VNodeCreatorRole` at cluster start-up time

### PR DESCRIPTION
**Pull request by vkolomeyko**
New E2E test been added. Also the roles been tested locally using combined worker.

### CODE REVIEW

**Review by davidcurrie — APPROVED** [review]
Might be preferable if the commands were idempotent (rather than returning an error if run again) but otherwise LGTM

**Comment by vkolomeyko** [comment]
> Might be preferable if the commands were idempotent (rather than returning an error if run again) but otherwise LGTM

Thanks @davidcurrie 
I was thinking of it. IMO running again when not necessary should give an indication to the caller that they might be doing something wrong. Hence non-zero error code returned by the CLI tool.
But I do not have a strong opinion here.

**Comment by davidcurrie** [comment]
> But I do not have a strong opinion here.

Me neither so happy to leave it as-is for now.

**Review by pmck91 — APPROVED** [review]

**Review by conal-smith — APPROVED** [review]
lgtm

**Pull request merged**
