### PR TITLE
CORE-6374 - Add max limit for inbound messages received from gateway

### PR DESCRIPTION
**Pull request by dimosr**
### Changes
Adding max limits for variable-length fields to prevent malicious clients from trying to trigger large allocations. Avro does not allow to define limits on a per-field basis in the schemas, so we need to resort to doing that globally via the available system properties. The current limit is set based on the fact that Corda will eventually have support for large objects, so anything larger than 5MB should be chunked.

Switched gateway from `fromByteBuffer` / `toByteBuffer` methods to avro schema registry's `serialise` / `deserialise` methods to ensure all the associated metadata are captured.

### Testing
Tested by decreasing the limit value and confirmed that gateway would fail at the point it would try to deserialise an incoming request with 400 and the associated connection would be closed.

Also added an integration test to capture against potential regressions during upgrade of the Avro libraries.

### CODE REVIEW

**Review by yift-r3 — DISMISSED** [review]
LGTM

**Comment by williamvigorr3** [comment]
Should we test this? (incase org.apache.avro.limits.bytes.maxLength got removed and we upgraded the version of avro).

**Comment by dimosr** [comment]
Looking into it..

**Comment by dimosr** [comment]
Ready for another look now (with the test in and move to avro schema registry)

**Review by yift-r3 — APPROVED** [review]

**Review by williamvigorr3 — APPROVED** [review]
LGTM

**Pull request merged**
