### PR TITLE
CORE-1645: Sandbox integration for CPK in flow worker.

### PR DESCRIPTION
**Pull request by luca-debiasi-r3**
Ready for review.

### CODE REVIEW

**Review by luca-debiasi-r3 — COMMENTED** [review]
Ready for review.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Documentation checked after modifications about log handling.
Ready for review.

**Review by JamesHR3 — CHANGES_REQUESTED** [review]
Few bits and pieces to change here. I'm also a little concerned about the API provided by install/sandboxing, which we might want to discuss just to make sure we're using it correctly before giving some feedback to the team.

**Review by JamesHR3 — COMMENTED** [review]
Some answers and a few formatting things.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Synchronized with the release branch, CR implemented as much possible today.
Full build OK. 
Corda plugin versions mismatch  requires  some literals versions in place.

**Review by JamesHR3 — COMMENTED** [review]
You've ended up with some other commits in your PR here. Think you need to rebase again.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Rebased onto release.
CR implemented.

**Review by luca-debiasi-r3 — COMMENTED** [review]
I acknowledge all changes.

**Review by JamesHR3 — CHANGES_REQUESTED** [review]
We seem to have the same concept implemented twice in different ways in `testing` and `applications/examples`, and you've rejigged the unit tests for the bootstrapper. There was no need to do that, this was really just about putting a demo together for using the sandbox. Can you undo that and just think about the sandbox demo app in this PR please?

If you were also thinking about an integration test, that should be standalone - definitely not tied to the bootstrapper testing, as that really should be unit testing the bootstrapper itself. (The fact that it depends on `framework-app-tester` is already a little questionable.)

**Review by luca-debiasi-r3 — COMMENTED** [review]
Rebased correctly (I hope!), documented and tested against last C5 install, packaging and sandbox services. All CR implemented or 'contested' with my rationales.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Ready for review.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Ready for review after complete rebase.

**Review by JamesHR3 — COMMENTED** [review]
If you haven't already, you'll need to rebase this to pick up the build dependency change.

I'm still really uncomfortable about having all our bootstrapper testing tied to sandboxing. I'd much rather the bootstrapper testing has as few dependencies as possible - that way people developing sandboxing code don't have to worry about accidentally breaking bootstrapper tests.

**Review by luca-debiasi-r3 — COMMENTED** [review]
Suggestions implemented.
I will provide `:testing:apps:test-app` module as I complete *flask* integration.

**Pull request closed without merging**
