### PR TITLE
CORE-5076 - Changing plugin generation to use Jar file, fixing an issue with plug…

### PR DESCRIPTION
**Pull request by pmck91**
…ins failing to load on various linux distros

### CODE REVIEW

**Comment by vkolomeyko** [comment]
@chrisr3 @ronanbrowne - I would very much appreciate you input here as Gradle experts. Also it seem like we are duplicating some code here across plugins. Perhaps, it would make sense to refactor it into common area inside `buildSrc` - WDYT?

**Comment by chrisr3** [comment]
> @chrisr3 @ronanbrowne - I would very much appreciate you input here as Gradle experts. Also it seem like we are duplicating some code here across plugins. Perhaps, it would make sense to refactor it into common area inside `buildSrc` - WDYT?

To be honest, I am thinking "I had _no idea_ this module even existed before I saw this PR..."

**Comment by chrisr3** [comment]
You probably also want to exclude any `module-info.class` and `META-INF/versions/*/module-info.class` files from the "fat jar".

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Comment by vkolomeyko** [comment]
@benmcmahon100 - would you be able to review and approve this PR on behalf of @corda/blt ?

**Pull request merged**
