### PR TITLE
CORE-18839 - Move Postgresql and MSSQL JDBC drivers to version catalog.

### PR DESCRIPTION
**Pull request by driessamyn**

### CODE REVIEW

**Review by yift-r3 — APPROVED** [review]

**Review by wzur-r3 — APPROVED** [review]
LGTM for Gradle configuration files

**Review by josephzunigadaly — APPROVED** [review]

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by kyriathar — APPROVED** [review]

**Review by LWogan — APPROVED** [review]

**Review by ben-millar — APPROVED** [review]
LGTM – flow worker

**Review by jennyang-r3 — APPROVED** [review]

**Review by nkovacsx — APPROVED** [review]
LGTM

**Pull request merged**
