### PR TITLE
CORE-12872 rename net.cordapp to com.r3.corda

### PR DESCRIPTION
**Pull request by vlajos**
CORE-12872 Rename `net.cordapp...` packages to `com.r3.corda...`

### CODE REVIEW

**Review by blsemo — APPROVED** [review]
LGTM

**Review by lankydan — APPROVED** [review]
Just to check you did a find and replace and also searched for all packages with `net.cordapp` in it?

**Comment by vlajos** [comment]
> Just to check you did a find and replace and also searched for all packages with `net.cordapp` in it?

I went through the gradle modules that `ugrep -rin --exclude-dir={.git,logs} net.cordapp` found.
I used intellij's refactoring for the module renames.

Then used these two for the remaining:
```
sed -i ''  -e 's/net.cordapp/com.r3.corda/g' $( ugrep -rinl --exclude-dir={.git,build,logs} net.cordapp|grep -v bin)
sed -i ''  -e 's/com.r3.corda.bundle/com.r3.corda.testing.bundle/g' $( ugrep -rinl --exclude-dir={.git,build,logs} com.r3.corda.bundle|grep -v bin)
```
(`com.r3.corda.bundle` seemed to be a bit too generic. So I added `testing` to it.)
Then I needed to regenerate the two `bin` files in the serialization-amqp integration tests.
(And there was an unused import somewhere around the dog files.)

And the end result:
```
ugrep -rin --exclude-dir={.git,logs} net.cordapp|wc
       0       0       0
```

**Review by mcgovc — APPROVED** [review]
LGTM - build file changes

**Review by lankydan — APPROVED** [review]
Double checked packages for `cordapp` and didn't see any `net.cordapp` lingering around

**Review by kyriathar — APPROVED** [review]

**Pull request merged**
