### PR TITLE
CORE-7934: Make the import certificate API clearer

### PR DESCRIPTION
**Pull request by yift-r3**
Change the path of the import certificate requests to explicitly differentiate between a cluster certificate and a node certificate.

### CODE REVIEW

**Comment by JamesHR3** [comment]
Do the different verbs prevent the clash between `cluster/{usage}` and `{tenantId}/{keyId}`?

**Comment by charlieR3** [comment]
Looks OK to me. This should be announced to the engineering and QA groups before merging so they are aware of the change.

**Comment by yift-r3** [comment]
The `cluster/{usage}` is `PUT` and the `{tenantId}/{keyId}`is `POST` - so it should be OK.

**Comment by dimosr** [comment]
Can we also add description on the PR, please?

**Review by vkolomeyko — APPROVED** [review]
LGTM

Also FAO: @davidcurrie and @jujoramos as this may have an impact on Soak testing environment bootstrapping.

**Review by charlieR3 — APPROVED** [review]
LGTM. 
Be sure to post this in the platform channel before merging though. QA and David Currie's team will want to know about this also since they have tests outside of the reuntime-os repo that won't be caught by the PR gate.

**Comment by jujoramos** [comment]
@vkolomeyko : thanks for the update, I'll open a `PR` to update both `soak` and `resiliency` tests shortly (won't merge until this one makes it to the release branch, though).

**Pull request merged**
