### PR TITLE
CORE-7113 - HikariCP metrics

### PR DESCRIPTION
**Pull request by driessamyn**
Update HikariCP version which now allows us to enable the micrometer metrics support.

### CODE REVIEW

**Review by nikinagy — DISMISSED** [review]
LGTM (network)

**Review by LWogan — DISMISSED** [review]

**Review by mcgovc — DISMISSED** [review]
LGTM

**Review by blsemo — DISMISSED** [review]
LGTM

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by mcgovc — APPROVED** [review]

**Review by kyriathar — APPROVED** [review]
OK (db)

**Review by lankydan — APPROVED** [review]

**Review by LWogan — APPROVED** [review]

**Review by nikinagy — APPROVED** [review]
LGTM (network)

**Pull request merged**
