### PR TITLE
CORE-4982: cpb version must be a positive int, supply a default value of 1

### PR DESCRIPTION
**Pull request by dickon**

### CODE REVIEW

**Review by driessamyn — APPROVED** [review]
LGTM.

**Comment by kyriathar** [comment]
Please hold on with this one. I can see for example in `sandbox-cpk-one` module its gradle.build file cordapp section being:

```
cordapp {
    targetPlatformVersion 999 as Integer
    workflow {
        name 'Sandbox CPK-1'
        versionId 1
        vendor 'R3'
    }
}
```
However in produced cpb Manifest file I can see `Corda-CPB-Version: 5.0.0.0-SNAPSHOT`.

@josephzunigadaly could you please advice here.

**Comment by kyriathar** [comment]
Seems `cordapp/workflow/versionId` being CPK's (included in CPB) `Cordapp-Workflow-Version` attribute.

**Comment by josephzunigadaly** [comment]
Kyriakos is right about the version numbers. Might be better to check it's not the empty string and leave it at that.

Please don't merge this as it is.

**Pull request closed without merging**
