### PR TITLE
CORE-7976 Move cipher-suite module from corda-api to corda-runtime-os

### PR DESCRIPTION
**Pull request by kyriathar**
api PR: [#695](https://github.com/corda/corda-api/pull/695)

### CODE REVIEW

**Review by chrisr3 — DISMISSED** [review]
LGTM

**Review by mnesbit — DISMISSED** [review]
OK

**Review by mnesbit — APPROVED** [review]
OK

**Review by ronanbrowne — APPROVED** [review]
lgtm build

**Review by conal-smith — APPROVED** [review]
LGTM from "rpc" perspective

**Pull request merged**
