### PR TITLE
CORE-13796:  Merge from `5.0` up to 8e67bda9

### PR DESCRIPTION
**Pull request by vkolomeyko**
Merge up to: 8e67bda9e86441b13e292be585f9490cf9e457a3

### CODE REVIEW

**Review by vlajos — APPROVED** [review]
The version number increase looks good to me. (I'll create another PR shortly to update the number to the proper 5.1 one and centralize the scattered hard-coded magic numbers.)

**Review by dimosr — APPROVED** [review]
Approving the Netty upgrade

**Review by kyriathar — APPROVED** [review]
OK (packaging)

**Review by thiagoviana — APPROVED** [review]
Approving the reduction of the external event retry period

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Pull request merged**
