### PR TITLE
CORE-14658: merge 5.0 work to 5.1

### PR DESCRIPTION
**Pull request by dickon**

### CODE REVIEW

**Comment by dickon** [comment]
Added @josephzunigadaly since this merge PR picked up one of his commits to confirm the merge was okay. There were no conflicts.

**Review by josephzunigadaly — APPROVED** [review]
My change looks good

**Review by mag1c-48 — APPROVED** [review]
LGTM (build only)

**Review by kyriathar — APPROVED** [review]

**Review by mbrkic-r3 — APPROVED** [review]
LGTM

**Pull request merged**
