### PR TITLE
CORE-15470 - Build JAVA 17 docker images.

### PR DESCRIPTION
**Pull request by driessamyn**
- Update the docker base image to the Java 17 JVM.
- Remove the J17 nightly build file.

### CODE REVIEW

**Review by chrisr3 — DISMISSED** [review]
Is that all it takes to upgrade our deployments to run on Java 17? :exploding_head:

**Comment by driessamyn** [comment]
> Is that all it takes to upgrade our deployments to run on Java 17? 🤯

Unfortunately not. I thought this would build J17 images but from looking at the E2E test logs, it doesn't look like it. I'll catch up with @ronanbrowne

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Comment by driessamyn** [comment]
Confirmed workers execute on 17 JVM: 
```
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] Picked up JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] WARNING: A terminally deprecated method in java.lang.System has been called
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] WARNING: System::setSecurityManager has been called by org.apache.felix.framework.Felix (file:/opt/override/flow-worker.jar)
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.Felix
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] WARNING: System::setSecurityManager will be removed in a future release
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:26.406 [main] INFO  net.corda.securitymanager.internal.SecurityManagerServiceImpl {} - Starting restrictive Corda security manager.
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:26.430 [main] INFO  net.corda.securitymanager.internal.SecurityManagerServiceImpl {} - Applying default security policy (high_security.policy)
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:42.299 [main] INFO  net.corda.securitymanager.internal.SecurityConfigHandlerImpl {} - SecurityConfigHandler started
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:46.391 [main] WARN  net.corda.osgi.framework.OSGiFrameworkWrap {} - OSGi bundle bundles/snappy-java-1.1.10.1.jar ID = 167 org.xerial.snappy.snappy-java 1.1.10.1 starting activation time-out after 0 ms.
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.689 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - Flow worker starting.
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.788 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - LocalWorkerPlatformVersion 50100
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.788 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - LocalWorkerSoftwareVersion 5.1.0.0-alpha-1689591907331
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.791 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - PID: 1
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.792 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - Command: /usr/lib/jvm/zulu17-ca-amd64/bin/java
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 0, -Dlog4j2.debug=false
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 1, -Dlog4j.configurationFile=/etc/log4j/log4j2.xml
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 2, -jar
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 3, /opt/override/flow-worker.jar
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 4, --workspace-dir=/work
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 5, --temp-dir=/tmp
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 6, -mbootstrap.servers=prereqs-kafka:9092
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 7, -msasl.jaas.config=[REDACTED]
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 8, --topic-prefix=bob
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 9, -msecurity.protocol=SASL_SSL
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 10, -msasl.mechanism=SCRAM-SHA-256
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.793 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 11, -mssl.truststore.location=/certs/ca.crt
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 12, -mssl.truststore.type=PEM
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 13, -spassphrase=[REDACTED]
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 14, -ssalt=qik7HLQoOScptlQFxxEZNrRwQVT4smTB
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - argument 15, --trace-samples-per-second=1
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - User: Null
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - StartInstant: 2023-07-17T11:19:17.460Z
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - TotalCpuDuration: PT36.04S
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.794 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - classpath: /opt/override/flow-worker.jar
[pod/corda-bob-flow-worker-7cd5ddc8d-hqwhj/corda-bob-flow-worker] 11:19:53.795 [main] INFO  net.corda.applications.workers.flow.FlowWorker {} - VM OpenJDK 64-Bit Server VM Azul Systems, Inc. 17.0.4.1+1-LTS
```
@chrisr3 FYI

**Comment by driessamyn** [comment]
Green E2E test build: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda5-e2e-tests/detail/release%2F5.1/408/pipeline

**Review by dickon — APPROVED** [review]
LGTM

So we'll drop 11 when this goes in?

**Review by yarivus — APPROVED** [review]
LGTM

**Review by jujoramos — APPROVED** [review]

**Pull request merged**
