### PR TITLE
CORE-20763 - Eliminate support of DurableStream

### PR DESCRIPTION
**Pull request by filipesoliveira**
`DurableStream` functionality is redundant in REST API and is never used in production to deliver any sort of feed. Therefore any references to `net.corda.rest.durablestream` have been removed from the codebase.

The following tests must be green before merging the PR:
- Unit tests (Done)
- Integration tests (Done)
- Smoke tests (Done)
- E2e tests (Done)
- QA regression tests (Done)

### CODE REVIEW

**Comment by filipesoliveira** [comment]
build e2e

**Comment by filipesoliveira** [comment]
build e2e

**Comment by filipesoliveira** [comment]
The Q.A. regression tests are now being run.

References:
- Jenkins build for the Q.A. regression tests - https://ci05.dev.r3.com/job/QA/job/CRAFT5/job/Craft_Tests/job/C5/job/Latest/job/Opensource/job/EKS/job/OS-qa-regpack-tests-rest-eks/job/main/

**Comment by filipesoliveira** [comment]
Q.A. regression is green.

References:
Jenkins pipeline with green build: https://ci05.dev.r3.com/job/QA/job/CRAFT5/job/Craft_Tests/job/C5/job/Latest/job/Opensource/job/EKS/job/OS-qa-regpack-tests-rest-eks/job/main/25/

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
