### PR TITLE
CORE-16623 : Sync with release

### PR DESCRIPTION
**Pull request by SaurabhR3**

### CODE REVIEW

**Review by ac101m — APPROVED** [review]
LGTM

**Review by wzur-r3 — CHANGES_REQUESTED** [review]
Please fix the PR title

Also if you are interested in pull requests created automatically for synchronisation, the Build team can assist.

**Comment by SaurabhR3** [comment]
> Please fix the PR title
> 
> Also if you are interested in pull requests created automatically for synchronisation, the Build team can assist.

@wzur-r3 That will be helpful, How can we create the sync pr automatically?

**Comment by ac101m** [comment]
> Please fix the PR title

There's no ticket associated with this pull request.

> Also if you are interested in pull requests created automatically for synchronisation, the Build team can assist.

We typically merge only when significant changes have been made to code that we have extended in our feature branch. There is no set schedule for this as it depends on what work is going on at the time. Scheduled merges are likely to cause more issues for us than they'll solve.

**Review by wzur-r3 — APPROVED** [review]
LGTM

**Pull request merged**
