### PR TITLE
CORE-0000: Merge from Corda 5.0 up to 1ea33b2

### PR DESCRIPTION
**Pull request by chrisr3**
Merge from release/os/5.0 up to 1ea33b2b638811d8d515bddbdae76ec65ecc5555.

### CODE REVIEW

**Review by charlieR3 — APPROVED** [review]
LGTM for my commit (91cea093a0fb58b957306033bd1d53f503073d3e)
@YashNabar is on PTO until the end of next week so I check his commit (da9d9bb17bb94dc6b181784b145585336e9a2c2b) and it looks good also

**Review by vkolomeyko — APPROVED** [review]
LGTM
(on behalf of @corda/rest)

**Review by kyriathar — APPROVED** [review]
LGTM (db, packaging & crypto)

**Review by wzur-r3 — APPROVED** [review]
LGTM for Gradle files

**Pull request merged**
