### PR TITLE
CORE-7040 Renaming remaining classes and modules from 'httprpc' to 'rest'

### PR DESCRIPTION
**Pull request by ben-millar**
This PR satisfies the following stories, which were each carried out on the `bm/CORE-7040` branch to avoid noise on mainline:
- [CORE-10592](https://r3-cev.atlassian.net/browse/CORE-10592): Changes to `permission-rpc-ops-impl` module
- [CORE-10593](https://r3-cev.atlassian.net/browse/CORE-10593): Changes to `components/configuration-rpc-ops-impl` module
- [CORE-10595](https://r3-cev.atlassian.net/browse/CORE-10595): Changes to `Annotation.isHttpRpcParameterAnnotation()` extension
- [CORE-10596](https://r3-cev.atlassian.net/browse/CORE-10596): Changes to `HttpRpcClientUtils` class
- [CORE-10597](https://r3-cev.atlassian.net/browse/CORE-10597): Changes to `HttpRpcCommand` class
- [CORE-10607](https://r3-cev.atlassian.net/browse/CORE-10607): Changes to `components.rpc` package

There's one more RPC->REST renaming task pending after this, but it will be done as a standlone PR into mainline as it touches 400+ files for directory and import renamings.

[CORE-10592]: https://r3-cev.atlassian.net/browse/CORE-10592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-10593]: https://r3-cev.atlassian.net/browse/CORE-10593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-10595]: https://r3-cev.atlassian.net/browse/CORE-10595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-10596]: https://r3-cev.atlassian.net/browse/CORE-10596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-10597]: https://r3-cev.atlassian.net/browse/CORE-10597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-10607]: https://r3-cev.atlassian.net/browse/CORE-10607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mag1c-48 — APPROVED** [review]
LGTM - build

**Review by ronanbrowne — APPROVED** [review]
lgtm (only build files reviewed however)

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by charlieR3 — APPROVED** [review]
LGTM from a network team perspective

**Pull request merged**
