### PR TITLE
CORE-7011: update Gradle to 7.5.1 + various plugins bumps

### PR DESCRIPTION
**Pull request by ronanbrowne**
- Bump Gradle to 7.5.1 - [release notes](https://docs.gradle.org/7.5.1/release-notes.html)
- update various Gradle Ent related plugins to latest version
- gradlew / gradlew.bat changes auto generated by Gradle

### CODE REVIEW

**Review by yarivus — DISMISSED** [review]
LGTM

**Review by chrisr3 — COMMENTED** [review]
Have any of Gradle's own files changed, ? E.g. try the following:
```bash
$ ./gradlew --stop
$ ./gradlew wrapper
$ ./gradlew clean
$ git status
```

**Comment by ronanbrowne** [comment]
> ```shell
> git status
> ```

@chrisr3 indeed, thanks for spotting that - updated.

**Review by chrisr3 — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Pull request merged**
