### PR TITLE
CORE-5401 Trusted Root Certificates - Add DB table to store trusted root certificates

### PR DESCRIPTION
**Pull request by mbrkic-r3**
- Added DB table to store trusted root certificates for packaging verification

### CODE REVIEW

**Review by josephzunigadaly — APPROVED** [review]

**Comment by charlieR3** [comment]
I'm not so familiar with what you're working on here but I'm wondering if there's some overlap with functionality we worked on on the MGM team. 
We added the ability to upload and persist certificates to a cluster previously (see `ClusterCertificate` entity or `CertificatesClient` for upload client)

**Comment by mbrkic-r3** [comment]
> ClusterCertificate

@charlieR3 We need to store trusted certificates for packaging validation (CPK/CPB/CPI). Was that envisioned to be reused buy components other than crypto, should we use it?

**Comment by charlieR3** [comment]
> 



> > ClusterCertificate
> 
> @charlieR3 We need to store trusted certificates for packaging validation (CPK/CPB/CPI). Was that envisioned to be reused buy components other than crypto, should we use it?

@mbrkic-r3 We've kept it quite generic at the moment but we've intended it for use for uploading cluster level certificates for either P2P TLS or RPC-API TLS , and virtual node level certificates for P2P session initiation. 

I assume the packaging validation certs would be cluster level so `CertificatesProcessor` would need to be adjusted to support an additional tenant ID. 

Our tables look very similar so it could make sense to combine them. The only difference at the cluster level between the two tables (yours and ours) is that our table specifies usage (P2P or RPC). This could be a future improvement either to come back to and review. I just wanted to point it out since they are so similar.

**Comment by driessamyn** [comment]
Thanks for highlighting this @charlieR3 
Not being too familiar with what's there, I'm not sure what's best. @mnesbit , do you have a view on whether we should re-use the P2P certificate table and upload APIs for the packaging "trusted certs", or if they should be kept separately?

**Comment by mbrkic-r3** [comment]
Closing as code signing certs can be stored in the existing cluster_certificates table that is used by P2P, for example (https://r3-cev.atlassian.net/wiki/spaces/CB/pages/3560505628/Decision+Log).

**Pull request closed without merging**
