### PR TITLE
CORE-14360: Merge 5.0 into 5.1

### PR DESCRIPTION
**Pull request by josephzunigadaly**
*Do not squash*

### CODE REVIEW

**Review by yift-r3 — APPROVED** [review]
My changes are already in 5.1

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by jujoramos — APPROVED** [review]
I've cherry-picked my changes from `5.1` into `5.0`, so my commit is already there.

**Review by mcgovc — APPROVED** [review]
LGTM - build changes

**Pull request merged**
