### PR TITLE
CORE-7312: Persistence and Verification sandbox groups should not include Flow CPKs

### PR DESCRIPTION
**Pull request by josephzunigadaly**
* Filters Verification and Persistence sandbox groups to only include contract CPKs

* Throws an exception on empty sandbox group

* Converts the following CPKs to contract CPKs:
     - components/ledger/ledger-persistence/testing-datamodel
     - testing/bundles/testing-cats
     - testing/bundles/testing-dogs
     - testing/bundles/testing-fish
     - testing/cpbs/sandbox-security-manager-one
     - testing/cpbs/sandbox-security-manager-two

* Extracts out classes to be used in Verification/ Persistence sandbox groups in new contract CPKs:
    - testing/cpbs/ledger-consensual-demo-contract
    - testing/cpbs/ledger-utxo-demo-contract

### CODE REVIEW

**Review by driessamyn — DISMISSED** [review]
LGTM

**Review by ronanbrowne — DISMISSED** [review]
lgtm - build

**Review by ronanbrowne — APPROVED** [review]
LGTM - build

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
