### PR TITLE
CORE-6687: Simulator handles exceptions and timeouts in flows

### PR DESCRIPTION
**Pull request by LizR3**
Configuration has been added for a clock, flow timeout and poll interval for exception handling.
Defaults are set to default clock, 1 minute and 100 ms respectively.
FlowMessaging picks up error from Responder and gives it to Initiator, which wraps and rethrows.
A warning is included in error message that real Corda will not provide the cause.
README updated.

### CODE REVIEW

**Review by driessamyn — COMMENTED** [review]
LGTM, but would be good for somebody from the Flow Worker team to have a look to.
Maybe @lankydan  or @JamesHR3 ?

**Review by lankydan — DISMISSED** [review]

**Review by mattbradburyr3 — DISMISSED** [review]
Approving based on discussion

**Comment by mattbradburyr3** [comment]
Making the call to merge this before Flow worker team review as it is relatively low risk. we can raise a further PR to correct if something material comes up later. This means we can make the RC04 cut off.

**Review by JamesHR3 — DISMISSED** [review]
Looks reasonable to me.

**Review by mattbradburyr3 — APPROVED** [review]

**Pull request merged**
