### PR TITLE
CORE-12187 - 31 March API Changes combined PR 2 (revision 742)

### PR DESCRIPTION
**Pull request by driessamyn**
PRs included:
- #3525 - CORE-12188 Switch to createTransactionBuilder function (@blsemo )
- #3506 - CORE-12143 Internalize OpaqueBytes and ByteSequence (@kyriathar )
- #3494 - CORE-9662: Make SignatureSpec an interface on public API  (@kyriathar / @anien )

### CODE REVIEW

**Review by dimosr — DISMISSED** [review]
approving for @corda/corda-platform-network-team files

**Review by dickon — APPROVED** [review]
LGTM for crypto

**Review by driessamyn — COMMENTED** [review]
Approved for #3506 and #3494

**Review by fowlerrr — APPROVED** [review]

**Review by kyriathar — APPROVED** [review]

**Review by ronanbrowne — APPROVED** [review]

**Review by blsemo — APPROVED** [review]
Looks ok re CORE-12188

**Review by dimosr — APPROVED** [review]

**Pull request merged**
