### PR TITLE
CORE-18912 - introduce version catalogue

### PR DESCRIPTION
**Pull request by driessamyn**

### CODE REVIEW

**Review by blsemo — DISMISSED** [review]
Looks ok to me.

**Review by dimosr — APPROVED** [review]
LGTM (for @corda/corda-platform-network-team files) - pending 🟢 build

**Review by JamesHR3 — APPROVED** [review]

**Review by anien — APPROVED** [review]
Is there a way to ensure everyone will use libs going forward?

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by dickon — APPROVED** [review]
LGTM (sandbox, crypto)

**Review by simon-johnson-r3 — APPROVED** [review]

**Review by ben-millar — APPROVED** [review]
LGTM for Flow

**Review by mbrkic-r3 — APPROVED** [review]
LGTM

**Review by blsemo — APPROVED** [review]

**Pull request merged**
