### PR TITLE
CORE-5418: Fix failing integration test

### PR DESCRIPTION
**Pull request by yift-r3**
It looks like the publisher needs to be created before the other databases.

To reproduce the error:
1. Create a database:
```
docker run --rm -d -p 5432:5432 --name postgresql -e POSTGRESQL_DATABASE=cordacluster -e POSTGRESQL_USERNAME=user -e POSTGRESQL_PASSWORD=password -e POSTGRESQL_POSTGRES_PASSWORD=password bitnami/postgresql:latest
```
2. Run the tests:
```
./gradlew \
	-P postgresHost=localhost \
	-P postgresPort=5432 \
	-P postgresDb=cordacluster \
	-P postgresUser=user \
	-P postgresPassword=password \
	:processors:member-processor:clean \
	:processors:member-processor:integrationTest
```

### CODE REVIEW

**Review by charlieR3 — DISMISSED** [review]
LGTM

**Review by fowlerrr — CHANGES_REQUESTED** [review]
I don't think this will work.  Actually, I'm surprised it's worked at all.  I'm going to hijack this PR and fix the DB message bus test set up.

**Review by alexey-kadyrov-r3 — APPROVED** [review]
LGTM for now as a quick fix but really there should be more permanent solution which won't depend on the order of initialisation in this case

**Review by fowlerrr — APPROVED** [review]

**Comment by fowlerrr** [comment]
Raised this for follow up: https://r3-cev.atlassian.net/browse/CORE-5768

**Review by charlieR3 — APPROVED** [review]

**Pull request merged**
