### PR TITLE
CORE-8810: Allow Custom Annotations in Helm Chart

### PR DESCRIPTION
**Pull request by jujoramos**
Update helm chart so users can add extra annotations (both globally
and individually) to corda worker pods.

### CODE REVIEW

**Review by davidcurrie — CHANGES_REQUESTED** [review]
For some reason, I ended up leaving comments on the commit rather than the PR. Hopefully, you still see them. Do you have a specific use-case in mind for this that would help motivate where the right places to use the annotations is?

**Comment by jujoramos** [comment]
> For some reason, I ended up leaving comments on the commit rather than the PR. Hopefully, you still see them. Do you have a specific use-case in mind for this that would help motivate where the right places to use the annotations is?

I didn't realise the comments were on the commit and also replied there instead of the `PR` 👎 .
Regarding the use case, `auto-scaler` is what I have in mind right now: all `corda` workers are currently configured as `Burstable` (only `requests` configured, no `limits`) and the `auto-scaler` might move them around when scaling down nodes.

**Comment by jujoramos** [comment]
After speaking with @davidcurrie offline, it was decided to leave the annotations as a top level field and apply them only to worker pods. A new ticket (`CORE-8819`) was created to further improve the chart and split those properties that are not common to both bootstrap `jobs` and worker `pods`.

**Review by davidcurrie — APPROVED** [review]
LGTM

**Pull request merged**
