### PR TITLE
CORE-15069 move flow to components

### PR DESCRIPTION
**Pull request by emilybowe**
Move two flow modules from libs to components. This will be used in future work to make use of a membership service in components to check clusters are local. Moving or copying this service was considered also but the move is also suggested for better design as these modules are closer to components than libs.

### CODE REVIEW

**Review by ben-millar — DISMISSED** [review]
```
  _____       ______  _________  ____    ____  
 |_   _|    .' ___  ||  _   _  ||_   \  /   _| 
   | |     / .'   \_||_/ | | \_|  |   \/   |   
   | |   _ | |   ____    | |      | |\  /| |   
  _| |__/ |\ `.___]  |  _| |_    _| |_\/_| |_  
 |________| `._____.'  |_____|  |_____||_____| 
```

**Review by ronanbrowne — DISMISSED** [review]
LGTM (build files changes only reviewed )

**Comment by thiagoviana** [comment]
As agreed, we're moving this to a feature branch, not 5.0 or 5.1.

**Comment by emilybowe** [comment]
Keeping this work in a feature branch for now, to avoid merging into 5.0 where possible. @thiagoviana

**Review by LWogan — APPROVED** [review]
LGTM. When ready, merge this to feature/CORE-15757/flow-session-refactor

**Review by wzur-r3 — APPROVED** [review]
LGTM for Gradle file change

**Pull request merged**
