### PR TITLE
CORE-5396 Convert all worker and CLI arguments to kebab case

### PR DESCRIPTION
**Pull request by williamvigorr3**
Convert all worker and CLI arguments to kebab case. To conform to the GNU standard https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html).

### CODE REVIEW

**Review by davidcurrie — DISMISSED** [review]
LGTM although it would be good to get a 👍 from @vkolomeyko as to whether this is a direction we'd also want to go in with the CLI

**Comment by vkolomeyko** [comment]
> LGTM although it would be good to get a 👍 from @vkolomeyko as to whether this is a direction we'd also want to go in with the CLI

I guess we could change CLI arguments to be kebab case as well, but this will also involve re-visting all the plugins and CLI commands created to date. Helm charts will also need to be updated since CLI is used to bootstrap the cluster.
FAO: @pmck91

**Review by ronanbrowne — DISMISSED** [review]
LGTM ( Jenkins file change ) but i'll defer to @vkolomeyko also for final say here prior to merge

**Review by vkolomeyko — DISMISSED** [review]
LGTM

**Comment by williamvigorr3** [comment]
> LGTM

Looking at the CLI params now.

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]

**Review by oscardalmau-r3 — APPROVED** [review]

**Pull request merged**
