### PR TITLE
CORE-11154 Remove `PublicKeyHash` from public API

### PR DESCRIPTION
**Pull request by kyriathar**
- moves/ internalizes `PublicKeyHash` from corda-api repo

api PR: [#901](https://github.com/corda/corda-api/pull/901)

### CODE REVIEW

**Review by charlieR3 — DISMISSED** [review]
LGTM

**Review by dickon — DISMISSED** [review]
LGTM.

**Review by charlieR3 — APPROVED** [review]

**Review by ronanbrowne — APPROVED** [review]
lgtm - build

**Review by dickon — APPROVED** [review]
LGTM

**Pull request merged**
