### PR TITLE
CORE-5165 DB based backing store for uniqueness checker

### PR DESCRIPTION
**Pull request by relyafi**
### Summary
This is a follow-on change from https://github.com/corda/corda-runtime-os/pull/1690, replacing the in-memory fake backing store with a real JPA based implementation. This is a port and refactor of the backing store implementation in the DP1 based code base in https://github.com/corda/corda5/pull/1614

For the time being, the uniqueness DB is hard-coded to use the `public` schema of the cluster DB. This will be revisited in subsequent changes to implement dynamic uniqueness DB selection based on a specified notary identity.

### Testing

- Uniqueness checker level unit tests continue to use the batched uniqueness checker with the fake in-memory backing store. Ensure these continue to pass.
- Uniqueness checker level integration tests have been introduced which use the batched uniqueness checker and JPA backing store. These have been run successfully using both HSQLDB and Postgres.
- Sanity check that both the DB worker and combined worker continue to start up successfully, and following initial startup, the uniqueness DB tables are present in the `public` schema of the cluster DB.

### CODE REVIEW

**Review by nkovacsx — DISMISSED** [review]
Happy with the changes!

**Review by nkovacsx — DISMISSED** [review]

**Review by ronanbrowne — DISMISSED** [review]
LGTM

**Review by ifrankrui — DISMISSED** [review]
LGTM

**Review by r3hj — DISMISSED** [review]
LGTM

**Review by nkovacsx — APPROVED** [review]

**Pull request merged**
