### PR TITLE
CORE-7100 Add getVirtualNode endpoint

### PR DESCRIPTION
**Pull request by Tom-Fitzpatrick**
Adds the getVirtualNode endpoint to VirtualNodeRpcOps. This returns the VirtualNodeInfo for the virtual node with the specified HoldingIdentityShorthash.

### CODE REVIEW

**Review by ronanbrowne — DISMISSED** [review]
LGTM (only build )- but needs a application developer review still.

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by conal-smith — APPROVED** [review]
Nice one, looks good!

**Review by ronanbrowne — APPROVED** [review]
lgtm

**Pull request merged**
