### PR TITLE
CORE-10597 HttpRpcCommand -> RestCommand

### PR DESCRIPTION
**Pull request by pmck91**

### CODE REVIEW

**Review by ben-millar — DISMISSED** [review]

**Review by ben-millar — DISMISSED** [review]
LGTM pending 🟢⚒️

**Review by YashNabar — DISMISSED** [review]
LGTM from a network team perspective

**Review by ronanbrowne — DISMISSED** [review]
lgtm - build pov

**Review by yift-r3 — APPROVED** [review]

**Review by ben-millar — APPROVED** [review]

**Review by mag1c-48 — APPROVED** [review]
LGTM build

**Pull request merged**
