### PR TITLE
NOTICK - Fix docs for API used to check registration progress

### PR DESCRIPTION
**Pull request by dimosr**
Slight adjustment to the docs for the API used to check registration progress to reflect the holding identity corresponds to the identity on behalf of which progress is checked (not the identity the registration corresponds to).

### CODE REVIEW

**Review by nikinagy — DISMISSED** [review]
LGTM

**Comment by nikinagy** [comment]
I just saw that we have the same wrong docs in `RegistrationStatusSpecificRpcRequest.avsc` too in corda-api. Can we do the same adjustment as in this PR there too?

**Comment by dimosr** [comment]
> I just saw that we have the same wrong docs in RegistrationStatusSpecificRpcRequest.avsc too in corda-api. Can we do the same adjustment as in this PR there too?

sure, I'll take a look.

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by nikinagy — APPROVED** [review]
LGTM

**Pull request merged**
