### PR TITLE
CORE-12581: run signing service direct from flow operations processor…

### PR DESCRIPTION
**Pull request by conal-smith**
This is a back-merge of https://github.com/corda/corda-runtime-os/pull/3801 from 5.1.

Please see Dickon's description there.

### CODE REVIEW

**Comment by rick-r3** [comment]
Looks like a worthwhile simplification, yes.  Beyond that, I'm not sure I can comment further.

**Review by jujoramos — COMMENTED** [review]
LGTM

**Review by jujoramos — COMMENTED** [review]
LGTM

**Comment by conal-smith** [comment]
Closed in favour of https://github.com/corda/corda-runtime-os/pull/3890

**Pull request closed without merging**
