### PR TITLE
NOTICK: Update Jackson dependency to 2.14.0

### PR DESCRIPTION
**Pull request by JamesHR3**
Updates the Jackson version to the latest, and folds the Jackson databind property back into the main Jackson property as per previous comments.

Upgrades:
jackson: 2.13.4.0 -> 2.14.0

### CODE REVIEW

**Review by ronanbrowne — DISMISSED** [review]
LGTM

**Review by vkolomeyko — DISMISSED** [review]

**Comment by vkolomeyko** [comment]
I have opened a related PR: #2554 into @JamesHR3 branch.

Also, I think the target of this PR has to be changed to Alpha branch.

**Review by vkolomeyko — APPROVED** [review]

**Review by ronanbrowne — APPROVED** [review]
lgtm

**Review by yarivus — COMMENTED** [review]
thx @ronanbrowne

**Pull request merged**
