### PR TITLE
CORE-18299: Use Interface Instead of Concrete Type

### PR DESCRIPTION
**Pull request by jujoramos**

### CODE REVIEW

**Review by vkolomeyko — DISMISSED** [review]
LGTM

**Review by YashNabar — DISMISSED** [review]
LGTM

**Comment by vkolomeyko** [comment]
Note: For this change to be merged into 5.2 branch, it would first need: https://github.com/corda/corda-runtime-os/pull/5083

**Comment by jujoramos** [comment]
> Note: For this change to be merged into 5.2 branch, it would first need: #5083

@vkolomeyko : why?, I'm failing to see the relationship between the two PRs?

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
