### PR TITLE
CORE-5405 Enabled package verification

### PR DESCRIPTION
**Pull request by mbrkic-r3**
- Enabled package verification
- Relaxed format 1 verification so that verification is successful for existing CPIs

Relaxed format 1 verification is implemented in a way that verification exception is caught and logged as warning. This will most likely log only errors related to package signatures (as that is checked first). Logging all errors would require wrapping code at different places where each verification check is performed which would require considerable refactoring.
Verification is relaxed just for package uploading. CLI packaging tool verification will still fail and it can be used resolve packing issues before uploading.

### CODE REVIEW

**Review by kyriathar — DISMISSED** [review]
We need to inform people how to import trusted signing certs before merging this (Working on it now).

**Comment by mbrkic-r3** [comment]
> We need to inform people how to import trusted signing certs before merging this (Working on it now).

Yes, I've used this for testing:
`curl --insecure -u admin:admin -X PUT -F alias="cordadev" -F certificate=@/tmp/cordadevcodesignpublic.pem https://localhost:8888/api/v1/certificates/codesigner`

We might also need to update documentation how to create CPB/CPI as following current documentation produces packages that don't validate successfully

**Comment by driessamyn** [comment]
> > We need to inform people how to import trusted signing certs before merging this (Working on it now).
> 
> Yes, I've used this for testing: `curl --insecure -u admin:admin -X PUT -F alias="cordadev" -F certificate=@/tmp/cordadevcodesignpublic.pem https://localhost:8888/api/v1/certificates/codesigner`
> 
> We might also need to update documentation how to create CPB/CPI as following current documentation produces packages that don't validate successfully

I'll leave the review to @josephzunigadaly , but we definitly need to update or create good documentation of the end-to-end process of creating a valid CPI and uploading it, and we should send an email with this ahead of the merge so to give people enough warning. We also need to include QA in this email too.

**Review by josephzunigadaly — DISMISSED** [review]
Looks good, just needs a rebase

**Review by josephzunigadaly — APPROVED** [review]

**Pull request merged**
