### PR TITLE
NOTICK-Remove unused cpk-service-common module

### PR DESCRIPTION
**Pull request by owenstanford**

### CODE REVIEW

**Comment by vkolomeyko** [comment]
CI build fails atm with: `Project with path ':components:virtual-node:cpk-service-common' could not be found in project ':components:virtual-node:cpk-read-service-impl'.`
https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2Fcorda-runtime-os/detail/PR-3260/1/pipeline

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by conal-smith — APPROVED** [review]
lgtm

**Review by ronanbrowne — APPROVED** [review]
lgtm (build)

**Pull request merged**
