### PR TITLE
CORE-17955 - Token Selection Remove Kafka RPC and merge existing Code with HTTP path

### PR DESCRIPTION
**Pull request by filipesoliveira**
Removed existing Kafka code from the token selection processor.
Merged the state and event processor pattern with the new delegated processor pattern and remove redundant code.
Refactored the code related to the merge.
Updated the unit tests accordingly.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
<p><b style="color:black" >Rule</b>: 26-GENERIC-PASSWORD<br>
    <b style="color:black" >Severity</b>:&nbsp;CRITICAL<br><b style="color:black">File</b>: .run/db-worker-local-debug.sh<br>
       <b style="color:black">Lines</b>: 10<br>
    <b style="color:black" >Scanner:</b> <a href="https://github.com/cider-rnd/secret-diver">Secret Diver</a></p>
    <details>
    <summary><b style="color:black">More Info</b></summary>
    Contains PASSWORD 
    </details><p><b style="color:black" >Rule</b>: 2-PEM-PRIVATE<br>
    <b style="color:black" >Severity</b>:&nbsp;CRITICAL<br><b style="color:black">File</b>: applications/workers/release/combined-worker/tls/rest/server.key<br>
       <b style="color:black">Lines</b>: 1<br>
    <b style="color:black" >Scanner:</b> <a href="https://github.com/cider-rnd/secret-diver">Secret Diver</a></p>
    <details>
    <summary><b style="color:black">More Info</b></summary>
    Contains a private key
    </details><p><b style="color:black" >Rule</b>: 2-PEM-PRIVATE<br>
    <b style="color:black" >Severity</b>:&nbsp;CRITICAL<br><b style="color:black">File</b>: docs/kafka/security/demo/certificates/ca/ca-key<br>
       <b style="color:black">Lines</b>: 1<br>
    <b style="color:black" >Scanner:</b> <a href="https://github.com/cider-rnd/secret-diver">Secret Diver</a></p>
    <details>
    <summary><b style="color:black">More Info</b></summary>
    Contains a private key
    </details><p><b style="color:black" >Rule</b>: 2-PEM-PRIVATE<br>
    <b style="color:black" >Severity</b>:&nbsp;CRITICAL<br><b style="color:black">File</b>: libs/rest/ssl-cert-read-impl/src/test/resources/server.key<br>
       <b style="color:black">Lines</b>: 1<br>
    <b style="color:black" >Scanner:</b> <a href="https://github.com/cider-rnd/secret-diver">Secret Diver</a></p>
    <details>
    <summary><b style="color:black">More Info</b></summary>
    Contains a private key
    </details>

**Comment by vkolomeyko** [comment]
Shall we run the E2E tests with binaries from this PR? (just to make sure we have not broken anything unintentionally)

**Comment by vkolomeyko** [comment]
Looks fine to me. @filipesoliveira - I have produced a PR https://github.com/corda/corda-runtime-os/pull/5110 with minor changes. It is completely up to you if you want to take them onboard.

**Comment by filipesoliveira** [comment]
> Looks fine to me. @filipesoliveira - I have produced a PR #5110 with minor changes. It is completely up to you if you want to take them onboard.

I have approved the PR.

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Comment by filipesoliveira** [comment]
> Shall we run the E2E tests with binaries from this PR? (just to make sure we have not broken anything unintentionally)

Yes, it is better to play it safe. Once the e2e tests are green I will leave a comment.

**Comment by filipesoliveira** [comment]
The e2e tests were green.

**Pull request merged**
