### PR TITLE
CORE-5913: Change how parameters passed into `KeysRpcOps.generateKeyPair`

### PR DESCRIPTION
**Pull request by vkolomeyko**
This eliminates the need for `GenerateKeyPairWrapperRequest` OpenAPI type.

### CODE REVIEW

**Comment by charlieR3** [comment]
@vkolomeyko why is this change necessary? 
I'm not a fan of the current path in the PR `{tenantId}/alias/{alias}/category/{hsmCategory}/scheme/{scheme}` 
Was there a problem with providing the properties in the body of the POST?

**Comment by vkolomeyko** [comment]
> @vkolomeyko why is this change necessary? I'm not a fan of the current path in the PR `{tenantId}/alias/{alias}/category/{hsmCategory}/scheme/{scheme}` Was there a problem with providing the properties in the body of the POST?

Hello @charlieR3 - it was not a problem as such. However, if we keep it as body parameters, as before an artificial type is created `...WrappedRequest` to represent in OpenAPI, which is not ideal.
The other thing is that we are trying to align our Restful API for along the pronciples described [here](https://restfulapi.net/rest-api-design-tutorial-with-example/), which encourages use of path parameters as per this PR.

**Comment by yift-r3** [comment]
Maybe we should change it to an object?

**Comment by vkolomeyko** [comment]
> Maybe we should change it to an object?

We can wrap it do a dedicated type to be used as a body parameter.
But I thought it would be more natural to use path parameters because:
1. They are all of simple type: string;
2. They are all required;
3. Should anyone would want to create a permission constraint - it is much easier to do against URL in the path rather than Body content.

**Review by yift-r3 — APPROVED** [review]

**Review by charlieR3 — APPROVED** [review]

**Pull request merged**
