### PR TITLE
CORE-6667 Expose connection pool maximum size

### PR DESCRIPTION
**Pull request by davidcurrie**

### CODE REVIEW

**Review by alexey-kadyrov-r3 — DISMISSED** [review]
LGTM

**Review by benmcmahon100 — DISMISSED** [review]
Looks good on my end. Only slight nit would be that it might be nice to set the bootstrap ones nice and high as I presume that'd speed up db bootstrap unless @driessamyn tells me I'm wrong

**Comment by davidcurrie** [comment]
> Looks good on my end. Only slight nit would be that it might be nice to set the bootstrap ones nice and high as I presume that'd speed up db bootstrap unless @driessamyn tells me I'm wrong

None of these apply to the DB bootstrapping - the ones configured in the `bootstrap` section are simply those written into the DB at bootstrap time.

**Comment by benmcmahon100** [comment]
> > Looks good on my end. Only slight nit would be that it might be nice to set the bootstrap ones nice and high as I presume that'd speed up db bootstrap unless @driessamyn tells me I'm wrong
> 
> None of these apply to the DB bootstrapping - the ones configured in the `bootstrap` section are simply those written into the DB at bootstrap time.

Ah but presumably, one can set the pool size for the initial migration no?

**Comment by davidcurrie** [comment]
> > > Looks good on my end. Only slight nit would be that it might be nice to set the bootstrap ones nice and high as I presume that'd speed up db bootstrap unless @driessamyn tells me I'm wrong
> > 
> > 
> > None of these apply to the DB bootstrapping - the ones configured in the `bootstrap` section are simply those written into the DB at bootstrap time.
> 
> Ah but presumably, one can set the pool size for the initial migration no?

This has yet to change from the code you wrote i.e. the actual execution is via `psql`

**Review by benmcmahon100 — APPROVED** [review]

**Pull request merged**
