### PR TITLE
CORE-8977 e2e test utilities

### PR DESCRIPTION
**Pull request by vlajos**
* CORE-8977 Move smoke test executor utilities to `testing/e2e-test-utilities`.
* Clean some dependencies
* CORE-8977 Publish `testing/test-utilities`
* Otherwise changes should be artifacts of package moves and detekt fixes.
* Successfully used here as well: https://github.com/corda/corda-e2e-tests/pull/2

### CODE REVIEW

**Review by owenstanford — COMMENTED** [review]
should the certificate.pem, cordadevcodesign.p12 and cordadevcodesign.pem be a specific test suite resource rather than ra resource of the utils? would we want test scenarios in e2e where we vary these?

**Comment by vlajos** [comment]
> should the certificate.pem, cordadevcodesign.p12 and cordadevcodesign.pem be a specific test suite resource rather than ra resource of the utils? would we want test scenarios in e2e where we vary these?

So far the tests worked with these resources.
I think we can update the approach when/if it is needed.

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]
lgtm - build

**Pull request merged**
