### PR TITLE
CORE-6662: Create `CordaDeveloperRole`

### PR DESCRIPTION
**Pull request by vkolomeyko**

### CODE REVIEW

**Review by conal-smith — DISMISSED** [review]
LGTM

**Review by davidcurrie — DISMISSED** [review]
👍 How many more roles are to come? I'm conscious that spinning up the JVM for each of this is steadily increasing the deployment time. We may need an aggregate "all" command at some point.

**Comment by vkolomeyko** [comment]
> 👍 How many more roles are to come? I'm conscious that spinning up the JVM for each of this is steadily increasing the deployment time. We may need an aggregate "all" command at some point.

This is the last one for now for the cluster creation time.
There will be one more at vNode creation time, but this will not require Helm Chart provisions.

**Comment by vkolomeyko** [comment]
> > 👍 How many more roles are to come? I'm conscious that spinning up the JVM for each of this is steadily increasing the deployment time. We may need an aggregate "all" command at some point.
> 
> This is the last one for now for the cluster creation time. There will be one more at vNode creation time, but this will not require Helm Chart provisions.

@davidcurrie - one more thought I had overnight...
There is a property (`.Values.bootstrap.rbac.enabled`) in `values.yaml` which may be used to disable this role creation business all together. As discussed, this is just a convenience and should have no impact on the performance run. It migth be a good idea to disable if we have many clusters to stand-up and want it to happen faster.

**Pull request merged**
