### PR TITLE
CORE-18168: Add new RBAC config sections to support bundle scripts

### PR DESCRIPTION
**Pull request by Tom-Fitzpatrick**

### CODE REVIEW

**Review by davidcurrie — DISMISSED** [review]
nit: the sections were in alphabetical order but there's no particular requirement for them to be... you could always argue that "role" comes after "representational"!

**Review by vkolomeyko — DISMISSED** [review]
LGTM

**Review by davidcurrie — APPROVED** [review]
🙇‍♂️

**Comment by Tom-Fitzpatrick** [comment]
> nit: the sections were in alphabetical order but there's no particular requirement for them to be... you could always argue that "role" comes after "representational"!

Ah, I hadn't spotted that, restored the alphabetical order now, might as well keep it, thanks :)

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
