### PR TITLE
CORE-7040: Rename RPC leftovers into REST

### PR DESCRIPTION
**Pull request by vkolomeyko**
Related PR: https://github.com/corda/corda-runtime-os/pull/3269

### CODE REVIEW

**Review by charlieR3 — APPROVED** [review]
LGTM from a network team perspective

**Review by conal-smith — APPROVED** [review]
LGTM

Just did a quick scan and I found a few more minor things we might want to change (maybe there are jira tickets for these already):
- https://github.com/corda/corda-runtime-os/blob/3502b7029e8869616ce18391311118589623639b/components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterProcessor.kt#L254
- what should be done about plugins-http-rpc? 
- Comment - https://github.com/corda/corda-runtime-os/blob/4e9a9cdc2663975f10a93e2f3259f23197218abb/components/virtual-node/virtual-node-rpcops-service-impl/src/main/kotlin/net/corda/virtualnode/rpcops/impl/v1/VirtualNodeRestResourceImpl.kt#L102
- This `rpc-api-tls` parameter in certificate chain import https://github.com/corda/corda-runtime-os/blob/2ea39a5df754b1427444bc4b1f32f0380aafbfac/components/membership/membership-rest/src/main/kotlin/net/corda/membership/rest/v1/CertificatesRestResource.kt#L56
- A few more references to HTTP RPC in KeysRestResource, HsmRestResource, CertificatesRestResource (above), these all appear in the public api swagger doc.
- HttpRpcCommand

**Comment by vkolomeyko** [comment]
> * VirtualNodeRestResourceImpl.kt

Thanks @conalsmith-r3 - let's address those as a separate PR once this one is merged.

**Review by ronanbrowne — APPROVED** [review]
lgtm

**Review by mag1c-48 — APPROVED** [review]
LGTM  (build)

**Comment by ben-millar** [comment]
Just a note: the `rpc-api` and `rpc-api-tls` refer to constants used in the CryptoWorker, and defined in corda-api avro files s o some care should be taken when changing them.

**Pull request merged**
