### PR TITLE
CORE-4714 In memory uniqueness checker implementation

### PR DESCRIPTION
**Pull request by relyafi**
### Summary

This change introduces an in-memory uniqueness checker component, which is designed to be used for testing purposes, and as an interim solution that can be developed against while the real uniqueness checker implementation is being developed.

The uniqueness checker component is packaged in its own processor, and is integrated in the DB worker. At this point, the processor is confirmed to be running, but it is not possible to interact with the processor on a real system due to no message protocol being implemented between the flow processor and uniqueness processor. Developing this is part of a separate track of work ([CORE-4726](https://r3-cev.atlassian.net/browse/CORE-4726)).

These changes have also developed a comprehensive set of unit tests which it should be possible to carry over in their entirety for testing the real uniqueness checker implementation when it is developed.

### Testing

A comprehensive set of unit tests have been added as part of this PR.

The uniqueness processor has also been confirmed to be running as part of the DB worker using the C5 development helm chart based deployment, by observing the logs of the DB worker pod.

### CODE REVIEW

**Review by dimosr — DISMISSED** [review]
Reviewed only the additions in the test-utilities - LGTM

**Review by nkovacsx — COMMENTED** [review]
Couple of minor comments, but generally looks good.

**Review by nkovacsx — DISMISSED** [review]
All my comments have been addressed, LGTM - seems like tests are failing though, might be flaky or something broke.

**Review by nkovacsx — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Pull request merged**
