### PR TITLE
CORE-15136 Moving selected flow smoketests to corda-e2e-tests repo

### PR DESCRIPTION
**Pull request by ben-millar**
This PR follows an initiative to move certain smoke tests from the `corda-runtime-os` repo to the `corda-e2e-tests` module. This means that the moved tests will run as part of the scheduled jenkins job rather than being part of the PR gate.

### CODE REVIEW

**Comment by ben-millar** [comment]
~~Blocked by: https://github.com/corda/corda-e2e-tests/pull/150~~
Unblocked, other PR is merged.

**Review by LWogan — COMMENTED** [review]
This looks fine, although im not 100% clear on the criteria for what stays in this repo and what should be moved.

edit: Spoke to ben on slack to clarify this, these changes makes sense to me.

**Review by LWogan — DISMISSED** [review]
LGTM

**Review by thiagoviana — DISMISSED** [review]
LGTM.

**Review by emilybowe — DISMISSED** [review]
LGTM

**Review by emilybowe — APPROVED** [review]
LGTM ! 👍

**Pull request merged**
