### PR TITLE
CORE-9724 Make `SecureHash` an interface on public API

### PR DESCRIPTION
**Pull request by kyriathar**
- implements `SecureHash` and updates use sites
- adds `parseSecureHash` static function to parse secure hashes in string form into `SecureHash` (ex public API `SecureHash.parse`)
- `DigestServiceImpl.parseSecureHash` to delegate to static `parseSecureHash` static function

api PR: [#925](https://github.com/corda/corda-api/pull/925)

### CODE REVIEW

**Review by driessamyn — DISMISSED** [review]
LGTM

**Review by vkolomeyko — DISMISSED** [review]
LGTM (on behalf of @corda/rest)

**Review by ronanbrowne — DISMISSED** [review]
lgtm - build

**Review by dimosr — DISMISSED** [review]
LGTM (@corda/corda-platform-network-team )

**Review by vkolomeyko — APPROVED** [review]

**Review by mnesbit — APPROVED** [review]
OK

**Review by ronanbrowne — APPROVED** [review]

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by dimosr — APPROVED** [review]

**Pull request merged**
