### PR TITLE
CORE-4806 skip e2etests locally if cluster unavailable

### PR DESCRIPTION
**Pull request by pmck91**
Skip e2e tests running locally (not Jenkins) if the K8s cluster is not responding, or not booted up.

### CODE REVIEW

**Review by conal-smith — COMMENTED** [review]
It looks good, but I don't see where it tells me the message "HTTP RPC Connection is down or not forwarded, skipping the test"?

This is shown when I run the tests from gradle, I don't actually know if they ran or not.
```
$ ./gradlew e2etest

> Configure project :
********************** CORDA FLOW WORKER BUILD **********************
SDK version: 11
JAVA HOME C:\Program Files\Java\zulu11.45.27
Corda runtime OS release version: 5.0.0.0-SNAPSHOT
Corda API dependency version spec: 5.0.0.108-beta+

BUILD SUCCESSFUL in 2m 27s
355 actionable tasks: 343 executed, 12 up-to-date
```

Guessing it might be important as a few comments are in the jira about it?

**Comment by vkolomeyko** [comment]
> It looks good, but I don't see where it tells me the message "HTTP RPC Connection is down or not forwarded, skipping the test"?
> 
> This is shown when I run the tests from gradle, I don't actually know if they ran or not.
> 
> ```
> $ ./gradlew e2etest
> 
> > Configure project :
> ********************** CORDA FLOW WORKER BUILD **********************
> SDK version: 11
> JAVA HOME C:\Program Files\Java\zulu11.45.27
> Corda runtime OS release version: 5.0.0.0-SNAPSHOT
> Corda API dependency version spec: 5.0.0.108-beta+
> 
> BUILD SUCCESSFUL in 2m 27s
> 355 actionable tasks: 343 executed, 12 up-to-date
> ```
> 
> Guessing it might be important as a few comments are in the jira about it?

Yes, I was also unable to see the reason reported anywhere.
@pmck91 - I think you wanted to check if there is a way to make this seen using some JUnit5 runner trick?

**Comment by vkolomeyko** [comment]
I have done some research on JUnit5/Gradle integration, in particular around outputting the reason why the test is skipped.
So far I found no way of getting hold of this information.
There is some information [here](https://github.com/gradle/gradle/issues/5511) and [here](https://roukou.org/2021/10/08/junit5-readable-reports-with-gradle/).
I think the underlying issue is that in Gradle `org.gradle.api.tasks.testing.TestResult` contains no information why the test was skipped. If it would be the case it would be possible to add a custom `testLogging` and output this information.

I feel we have made an improvement in this PR and I will approve and merge it.

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
