### PR TITLE
CORE-5088 Consensual Ledger Persistence

### PR DESCRIPTION
**Pull request by mbrkic-r3**
- Moved modules `entity-processor-service` and `entity-processor-service-impl` from `components:virtual-node` to `components:persistence`

### CODE REVIEW

**Review by ronanbrowne — DISMISSED** [review]
LGTM (build)

**Comment by omfR3** [comment]
:+1:

**Review by ronanbrowne — DISMISSED** [review]
LGTM (build)

**Comment by mbrkic-r3** [comment]
Reverted move of modules `ledger-persistence-service` and `ledger-persistence-service-impl` as they were moved to another place in the meanwhile with https://github.com/corda/corda-runtime-os/pull/2321

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Pull request merged**
