### PR TITLE
CORE-18839 - Move Caffeine to version catalog.

### PR DESCRIPTION
**Pull request by driessamyn**

### CODE REVIEW

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by anien — APPROVED** [review]
LGTM

**Review by yift-r3 — APPROVED** [review]

**Review by wzur-r3 — APPROVED** [review]
LGTM for Gradle configuration files

**Review by bpaunescu — APPROVED** [review]
LGTM

**Review by bpaunescu — APPROVED** [review]

**Pull request merged**
