### PR TITLE
CORE-4992: Create a ZIP artifact containing the YourKit profiler agent.

### PR DESCRIPTION
**Pull request by chrisr3**
This is a standalone Gradle build that creates a ZIP containing the Linux x86_64 version of the current YourKit Java profiler, and then publishes it to the `engineering-tools-maven-stable` repository in Artifactory. The ZIP file contains the following contents:
```
$ unzip -l yourkit-linux-x86-64-2022.3.zip 
Archive:  yourkit-linux-x86-64-2022.3.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  06-15-2022 13:06   YourKit/
        0  06-15-2022 13:06   YourKit/bin/
        0  06-15-2022 13:06   YourKit/bin/linux-x86-64/
  9589768  05-27-2022 16:32   YourKit/bin/linux-x86-64/libyjpagent.so
     1655  05-27-2022 16:32   YourKit/license-redist.txt
---------                     -------
  9591423                     5 files
```
This Java Profiler agent can be included into the applications' Docker images as follows:
```gradle
$ ./gradlew -PenableProfiling=true publishOSGiImage
```
Once you have published Docker images containing the profiling agent, you can enable profiling via Helm.

### CODE REVIEW

**Comment by mnesbit** [comment]
This isn't open source we can't merge it

**Comment by chrisr3** [comment]
> This isn't open source we can't merge it

We aren't including YourKit. This is only a Gradle project which downloads YourKit and extracts a redistributable ZIP from it. Open Source developers can execute this project themselves to create and publish the same ZIP to `mavenLocal()`. And they'd have to set `-PenableProfiling=true` to need it anyway.

We publish the ZIP to `engineering-tools-maven` in Artifactory, which is not publicly accessible.

**Review by davidcurrie — COMMENTED** [review]
LGTM but this needs input from someone in @corda/blt on the changes to the build structure. To @mnesbit's point, they should also comment on whether there is a better place for the `profiler` build to sit than `corda-runtime-os`.

As discussed with @chrisr3, there is a follow-on piece of work needed to actually expose building the agent into the images as an option on a CI build (disabled by default).

**Comment by chrisr3** [comment]
>To `@mnesbit`'s point, they should also comment on whether there is a better place for the `profiler` build to sit than `corda-runtime-os`.

It seems like the best place for it, because Open Source developers will need to use it to publish their own ZIP artifact into their local Maven repositories. You will notice that `profiler` does not contain any YourKit code itself.

**Review by driessamyn — APPROVED** [review]
LGTM

@ronanbrowne , we're merging this so it doesn't get held up, but would appreciate your retrospective review when you're back.
We should also talk about risks of publishing the docker image etc and any potential licence implications.

**Pull request merged**
