### PR TITLE
ES-2299: Remove the old rest-client module

### PR DESCRIPTION
**Pull request by tlawson3**
After we added the generated-rest-client the old rest-client isn't being used in the CLI anymore

### CODE REVIEW

**Comment by tlawson3** [comment]
build e2e

**Review by anton-subbotin — APPROVED** [review]
LGTM (Tooling team)

**Review by wzur-r3 — APPROVED** [review]
Approved changes for Gradle settings file

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Pull request merged**
