### PR TITLE
CORE-19467 Enable snappy compression

### PR DESCRIPTION
**Pull request by lankydan**
Enable snappy compression but also provide a way to serialize without
compression for our internal code.

This is needed for signature verification where we need to ensure that
signature verification works when communicating with 5.1 nodes who
cannot serialize with compression themselves. Turning off compression
here means that all parties whether on 5.1 or 5.2 will generate the same
byte output, allowing signatures to be verified.

### CODE REVIEW

**Review by ronanbrowne — APPROVED** [review]
LGTM (blt files only)

**Review by rick-r3 — APPROVED** [review]

**Review by ben-millar — APPROVED** [review]
LGTM — flow worker

**Review by simon-johnson-r3 — APPROVED** [review]

**Comment by lankydan** [comment]
build e2e

**Review by emilybowe — APPROVED** [review]
Possibly some of these serializationService variables that are now of type FlowSerializationService, could be called -> flowSerializationService
Just a nit though, (flow files reviewed only) LGTM 👍

**Pull request merged**
