### PR TITLE
CORE-16208 integration test for the event mediator

### PR DESCRIPTION
**Pull request by LWogan**
Add an integration test for the event mediator message pattern. Previously there were none. Added to the existing message pattern integration tests.
Add a test storage manager library which uses in memory maps so that postgres does not need to be span up to run the tests

### CODE REVIEW

**Review by ben-millar — APPROVED** [review]
```
    __    ______________  ___
   / /   / ____/_  __/  |/  /
  / /   / / __  / / / /|_/ / 
 / /___/ /_/ / / / / /  / /  
/_____/\____/ /_/ /_/  /_/  
```

**Review by thiagoviana — APPROVED** [review]

**Review by mbrkic-r3 — APPROVED** [review]
LGTM

**Review by mag1c-48 — APPROVED** [review]
LGTM - build only

**Review by mcgovc — APPROVED** [review]
LGTM

**Pull request merged**
