### PR TITLE
CORE-7123 Replace OTel with Prometheus

### PR DESCRIPTION
**Pull request by davidcurrie**
Remove the Open Telemetry agent from the worker images and add the ability to annotate the workers for Prometheus to scrape the `/metrics` endpoints.

### CODE REVIEW

**Comment by davidcurrie** [comment]
Example metrics scraped via Datadog agent:
image

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Review by oscardalmau-r3 — APPROVED** [review]
LGTM

**Review by yarivus — COMMENTED** [review]
Thanks @davidcurrie 
Have we decided to ditch OpenTel ?

**Comment by davidcurrie** [comment]
> Have we decided to ditch OpenTel ?
TL;DR yes - for now at least!

For metrics we are now using Micrometer for the API with the Prometheus registry which is giving us the same JVM metrics that we were previously getting from the Open Telemetry agent (hence this PR). If we subsequently decide that we'd like to switch back to a push model, there is a registry for Micrometer that speaks the Open Telemetry protocol i.e. from an external viewpoint we could still be "doing Open Telemetry" even if we're not using the Open Telemetry API or SDK. The subject of what we will use for trace is still open...

**Comment by driessamyn** [comment]
> Thanks @davidcurrie Have we decided to ditch OpenTel ?

FYI https://r3-cev.atlassian.net/wiki/spaces/CB/pages/3560505628/Decision+Log#corda-metrics

**Pull request merged**
