### PR TITLE
CORE-8984 Modify log4j to replicate bug

### PR DESCRIPTION
**Pull request by lankydan**

### CODE REVIEW

**Comment by vkolomeyko** [comment]
Does it have to be merged into the `main` branch?
Alternative approach I was thinking is to have this change in the `feature` branch and run CI builds as necessary via dedicated configuration to get to the bottom of the flakiness. It it also possible to create a Jenkins Cron job to trigger CI execution more frequently.

**Comment by lankydan** [comment]
> Does it have to be merged into the `main` branch? Alternative approach I was thinking is to have this change in the `feature` branch and run CI builds as necessary via dedicated configuration to get to the bottom of the flakiness. It it also possible to create a Jenkins Cron job to trigger CI execution more frequently.

I ran the test 100 times but couldn't get it to fail. If we really don't want to do this, then I can setup a cron job (Ronan told me how to do this when I was trying to replicate this bug before).

**Comment by vkolomeyko** [comment]
> I ran the test 100 times but couldn't get it to fail. If we really don't want to do this, then I can setup a cron job (Ronan told me how to do this when I was trying to replicate this bug before).

100 times is a decent count to claim stability, possibly the test is not flaky anymore? Or possibly it is a function in which order tests are executed?

**Comment by lankydan** [comment]
> > I ran the test 100 times but couldn't get it to fail. If we really don't want to do this, then I can setup a cron job (Ronan told me how to do this when I was trying to replicate this bug before).
> 
> 100 times is a decent count to claim stability, possibly the test is not flaky anymore? Or possibly it is a function in which order tests are executed?

Unfortunately, it seemed to fail on the release branch the other day. I thought the same since there were a few weeks between when I tried to replicate it and when it was first reported, but it still seems to happen.

**Comment by driessamyn** [comment]
> > > I ran the test 100 times but couldn't get it to fail. If we really don't want to do this, then I can setup a cron job (Ronan told me how to do this when I was trying to replicate this bug before).
> > 
> > 
> > 100 times is a decent count to claim stability, possibly the test is not flaky anymore? Or possibly it is a function in which order tests are executed?
> 
> Unfortunately, it seemed to fail on the release branch the other day. I thought the same since there were a few weeks between when I tried to replicate it and when it was first reported, but it still seems to happen.

I failed on one of my PRs yesterday, so I don't think we can claim it's stable.
I'm ok with this change going on, we should remember to turn it off the next beta release branch if it hasn't been resolved by then.

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by ronanbrowne — APPROVED** [review]
lgtm

**Pull request merged**
