### PR TITLE
CORE-19076: Bump kubernetesClientVersion to 6.9.2 and move to version catalog

### PR DESCRIPTION
**Pull request by jacob-scott3141**
Bump kubernetesClientVersion=6.7.2 -> 6.9.2

### CODE REVIEW

**Review by ronanbrowne — DISMISSED** [review]
LGTM

**Comment by jacob-scott3141** [comment]
build e2e

**Comment by vkolomeyko** [comment]
Should we also take this opportunity to migrate this library to Version Catalog?

**Comment by ronanbrowne** [comment]
> Should we also take this opportunity to migrate this library to Version Catalog?

Good point, I agree. 

@jacob-scott3141 feel free to reach out and I can give you an overview of needed change

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Pull request merged**
