### PR TITLE
CORE-19442: Move `jacksonVersion` to version catalog

### PR DESCRIPTION
**Pull request by vkolomeyko**
Just a transition to Jackson libraries to version catalog without trying to upgrade Jackson.
Hopefully, Dependabot will be able to do it automatically after this PR is merged.

### CODE REVIEW

**Review by blsemo — APPROVED** [review]
Fine from notary and ledger point of view

**Review by josephzunigadaly — APPROVED** [review]

**Review by anien — APPROVED** [review]
OK (crypto)

**Review by ronanbrowne — APPROVED** [review]
LGTM

**Review by yift-r3 — APPROVED** [review]

**Review by kyriathar — APPROVED** [review]
OK (sandboxing & packaging)

**Review by dimosr — APPROVED** [review]

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by mbrkic-r3 — APPROVED** [review]
LGTM

**Pull request merged**
