### PR TITLE
CORE-4354: Close streams

### PR DESCRIPTION
**Pull request by josephzunigadaly**
The Windows build detected one of these streams was left open. I went through usages and found a couple more cases.

Looking through this code, I found that CPKs are long lived objects. They held open a file for their lifetime. I've reworked this so they store the filename instead, opening and closing the file only when they want to read from it (in `getResourceAsStream`). As a result the `Cpi` and `Cpk` interfaces no longer need `AutoCloseable`. So you will see some `close` calls removed by this PR.

`CpiLoader` would filter CPKs, potentially losing the last reference without closing (found when they still needed closing). Inspection of the code leading up to this point showed that the filter would never remove CPKs so the filter call was removed along with an unnecessary use of nullable.

### CODE REVIEW

**Review by barrylapthorn — DISMISSED** [review]

**Review by mnesbit — DISMISSED** [review]
OK

**Comment by vkolomeyko** [comment]
It should be possible to trigger a Windows CI build for this branch to see if it solves all the issues.
Looks like it is failing atm: https://ci02.dev.r3.com/blue/organizations/jenkins/Corda5%2FNightlys%2FCorda-Runtime-OS%2FWindows/detail/PR-1417/7/pipeline
```
[2022-06-09T10:25:24.331Z] Caused by: java.nio.file.FileSystemException: C:\jenkins\workspace\corda5\nightlys\corda-runtime-os\windows\pr-1417\7\libs\sandbox-internal\build\tmp\testOSGi\junit15249806901514449749\6617A91641F370ED3E6911B2690743906E0C24285D6168E7BDBAA4C77DB71977: The process cannot access the file because it is being used by another process.
```

**Comment by josephzunigadaly** [comment]
Converted back to draft because I've found more issues to fix

**Comment by barrylapthorn** [comment]
Have a look for any `Files.list(...)` they need fixing as well ->  `Files.list(...).use { }` - but maybe you won't find any.

**Review by barrylapthorn — APPROVED** [review]
LGTM - though have a quick look for any `Files.list(...)` as per comment.

**Comment by josephzunigadaly** [comment]
> Have a look for any `Files.list(...)` they need fixing as well -> `Files.list(...).use { }` - but maybe you won't find any.

Thank you Barry. Just checked and it looks good. All had `.use {}`.

**Pull request merged**
