### PR TITLE
CORE-20497 - Eliminated `CpiIdentifier_1` in OpenAPI

### PR DESCRIPTION
**Pull request by filipesoliveira**
After applying the change the `CpiIdentifier_1` is no longer listed:
image

### CODE REVIEW

**Comment by vkolomeyko** [comment]
`processors/rest-processor/src/integrationTest/resources/swaggerBaseline-v*.json` files are likely to be needed updating. As `net.corda.processors.rest.OpenApiCompatibilityTest` is likely to fail.

**Comment by vkolomeyko** [comment]
build e2e

**Review by vkolomeyko — APPROVED** [review]
LGTM

I have triggered Engineering E2E build from this PR. It would probably make sense to run QA Regression as well to see if we broke anything with this change.

**Comment by vkolomeyko** [comment]
Looks like we have an [E2E test failure](https://ci02.dev.r3.com/job/Corda5/job/corda5-e2e-tests/job/GitComment-E2E-release%2F5.3/36/testReport/junit/net.corda.e2etest.virtualnode.externalmessaging/ExternalMessagingTest$ConfigTest/the_external_messaging_route_configuration_is_generated_correctly_when_a_CorDapp_has_channels_defined__/) which might be related to this change.
@filipesoliveira - could you please have a look?

**Comment by filipesoliveira** [comment]
The failing e2e test will be fixed once the PR https://github.com/corda/corda-e2e-tests/pull/628 is merged.

**Pull request merged**
