### PR TITLE
CORE-15757, CORE-16173 Session refactor and wakeup removal

### PR DESCRIPTION
**Pull request by LWogan**
API: https://github.com/corda/corda-api/pull/1208

### CODE REVIEW

**Review by williamvigorr3 — DISMISSED** [review]
LGTM (network team code)

**Review by mcgovc — DISMISSED** [review]
LGTM - build file changes (settings.gradle)

**Review by williamvigorr3 — DISMISSED** [review]
LGTM (network team code)

**Review by wzur-r3 — DISMISSED** [review]
LGTM for Gradle configuration file

**Review by charlieR3 — APPROVED** [review]

**Review by mbrkic-r3 — APPROVED** [review]

**Review by wzur-r3 — APPROVED** [review]
LGTM for Gradle configuration files

**Review by JamesHR3 — APPROVED** [review]
All changes approved in previous PRs.

**Pull request merged**
