### PR TITLE
CORE-15964: Revert "Add full HSQLDB support to ledger. (#4422)"

### PR DESCRIPTION
**Pull request by jujoramos**
This reverts commit fb9a468429be74dde95a3031b48b6492fac10cd5.

### CODE REVIEW

**Comment by chrisr3** [comment]
You realise that HSQLDB is a purely _**test**_ database, right?

**Comment by jujoramos** [comment]
> You realise that HSQLDB is a purely _**test**_ database, right?

Indeed, but some files updated through commit fb9a468429be74dde95a3031b48b6492fac10cd5 are not _**100% testing related only**_. This `PR` was just a test, that's why is marked as `Draft`.

**Comment by chrisr3** [comment]
> > You realise that HSQLDB is a purely _**test**_ database, right?
> 
> Indeed, but some files updated through commit [fb9a468](https://github.com/corda/corda-runtime-os/commit/fb9a468429be74dde95a3031b48b6492fac10cd5) are not _**100% testing related only**_. This `PR` was just a test, that's why is marked as `Draft`.

True, but:
```kotlin
props += configuration.extraProperties
```
 does nothing if `configuration.extraProperties` is an empty map, which it is for Postgres.

**Comment by jujoramos** [comment]
> > > You realise that HSQLDB is a purely _**test**_ database, right?
> > 
> > 
> > Indeed, but some files updated through commit [fb9a468](https://github.com/corda/corda-runtime-os/commit/fb9a468429be74dde95a3031b48b6492fac10cd5) are not _**100% testing related only**_. This `PR` was just a test, that's why is marked as `Draft`.
> 
> True, but:
> 
> ```kotlin
> props += configuration.extraProperties
> ```
> 
> does nothing if `configuration.extraProperties` is an empty map, which it is for Postgres.

True but, as I already said yesterday in offline communications: we didn't inspect the changes in details and, instead, tried a quick revert of the single commit that touched some files present in the stack trace we were seeing in our tests.
That said, commit fb9a468429be74dde95a3031b48b6492fac10cd5 doesn't have anything to do with the issue (as expected), so I'll close the `PR`.

**Pull request closed without merging**
